"""Repo Judge Tool for Agent

This tool provides agent access to the repo judge functionality,
allowing the agent to judge repository code based on rubric questions.
"""

from litellm import ChatCompletionToolParam

RepoJudgeTool: ChatCompletionToolParam = {
    "type": "function",
    "function": {
        "name": "repo_judge",
        "description": (
            "Judge repository code based on a rubric file. "
            "This tool analyzes the repository using aider for each rubric question from the file, "
            "then uses LLM to provide an overall summary of whether the repository satisfies the rubric. "
            "Useful for evaluating code quality, feature completeness, and adherence to requirements. "
            "\n\nWORKFLOW: This tool is typically used as the SECOND STEP in a paper evaluation workflow: "
            "1. First use paper_rubric to extract requirements from the paper and save to a rubric file "
            "2. Then use repo_judge with the generated rubric file to evaluate repository implementation"
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Path to the repository to be judged"
                },
                "rubric_file_path": {
                    "type": "string",
                    "description": "Path to rubric file (generated by paper_rubric tool) containing evaluation criteria"
                }
            },
            "required": ["repo_path", "rubric_file_path"]
        }
    }
} 